### ISSUE TITLE
Method to disengage (c) © shortcut

### ISSUE THREAD

**Issue by ggarcia0596** [gettypubs/restoration-ancient-bronzes#5]
Currently `(c)` is used as a shortcut to create the © symbol. I ran into the issue in figure captions where the text would say:
`**Figures 6.16a–c.** The Minerva’s internal wood support (and Carradori’s iron armatures for the head and right arm) and main stucco integration (a–b); thirty-two of the forty-four fixing nails extracted during the dismounting of the sculpture ( c )`

Without the extra spaces around the "c" it would create a © symbol.

Creating a way to nullify that shortcut for situations such as these or streamlining the text used to indicate subfigures would be effective to solve this issue.

**Comment by geealbers** [comment]
The way to do this is put a backslash (`\`) escape character in to tell the Markdown renderer not to convert it: `\(c)`. The backslash tells the rendered to render the proceeding character AS IS.

However, when you have text in YAML that is being rendered in Markdown (as in a figure caption like your example above) the escape character won't work when the text is in double quotes. Instead, you have to use a pipe character, and indent the Markdown text on the following line. (See my related comment on issue #4 about the pipe character.)

So this doesn't work:

```yaml
caption: "**Figures 6.16a–c.** The Minerva’s internal wood support (and Carradori’s iron armatures for the head and right arm) and main stucco integration (a–b); thirty-two of the forty-four fixing nails extracted during the dismounting of the sculpture \(c)"
```

But this does:

```yaml
caption: |
  **Figures 6.16a–c.** The Minerva’s internal wood support (and Carradori’s iron armatures for the head and right arm) and main stucco integration (a–b); thirty-two of the forty-four fixing nails extracted during the dismounting of the sculpture \(c)
```

**Comment by ggarcia0596** [comment]
Thank you! I've added that where it was needed.
